✨ feat: 예약 신청 기능 개발
Snap-Spot/snapspot-api pull request #35
Opened 2023-08-28 13:57 UTC by rovemin

## Details
- 예약 신청 기능 개발하였습니다.
- 스냅촬영 컨택의 다음 단계 api는 아직 개발 중입니다.
- Swagger는 아직 

## Image
<img width="1427" alt="image" src = "https://github.com/Snap-Spot/snapspot-api/assets/97473239/c4e09468-3fb4-4a30-a2d3-c76790ce0e27">

2023-08-28 17:19 UTC, sunnyineverywhere reviewed
.girignore에 .idea/ 추가해야 할 것 같아요. 그리고 빌드 파일 clean하시고 커밋해주시는 게 좋을 것 같습니다.

2023-08-28 17:19 UTC, sunnyineverywhere commented on snapspot-api/src/main/java/snap/api/member/dto/MemberResponseDto.java
>          this.role = entity.getRole();
혹시 Builder 패턴을 사용하는 부분이 있을까요? 아니라면 작성하신 이유가 궁금합니다.

2023-08-28 17:19 UTC, sunnyineverywhere commented on snapspot-api/src/main/java/snap/api/photographer/controller/PhotographerController.java
> +    }
PathVariable로 photographerId를 처리하기 보다, PlanRequestDto에 함께 넣어서 관리하는 건 어떨까요?

2023-08-28 17:19 UTC, sunnyineverywhere commented on snapspot-api/src/main/java/snap/api/plan/dto/request/PlanRequestDto.java
> +    }
오 JsonFormat 신기하네요 굿굿

2023-08-28 17:19 UTC, sunnyineverywhere commented on snapspot-domain/src/main/java/snap/domains/photographer/repository/PhotographerRepository.java
> +    Photographer findByPhotographerId(Long photographerId);
Optional로 감싸주세요!

2023-08-28 17:19 UTC, sunnyineverywhere commented on snapspot-domain/src/main/java/snap/domains/plan/entity/Plan.java
UUID 잘 생성되는지 사진 첨부해주실 수 있나요?

2023-08-28 17:19 UTC, sunnyineverywhere commented on snapspot-domain/src/main/java/snap/domains/plan/entity/Status.java
꼼꼼하게 해주셨네요 감사합니다

2023-08-28 17:24 UTC, rovemin commented on snapspot-api/src/main/java/snap/api/member/dto/MemberResponseDto.java
>          this.role = entity.getRole();
사용되는 부분 없는 것 같아서 이 부분은 수정하겠습니다.

2023-08-28 17:29 UTC, rovemin commented on snapspot-api/src/main/java/snap/api/photographer/controller/PhotographerController.java
> +    }
작가 상세페이지에서 예약이 진행되어서 PathVariable로 처리했었습니다. 
Dto로 관리해도 괜찮은 것 같다면 의견 반영해서 수정하겠습니다. Dto로 관리할 경우 Plan 도메인 내에서 개발이 가능하여 더욱 좋을 것 같습니다!

2023-08-28 17:30 UTC, rovemin commented on snapspot-domain/src/main/java/snap/domains/photographer/repository/PhotographerRepository.java
> +    Photographer findByPhotographerId(Long photographerId);
넵

2023-08-28 17:31 UTC, rovemin commented on snapspot-domain/src/main/java/snap/domains/plan/entity/Plan.java
PR 메세지에 첨부된 포스트맨 결과 이미지 보시면 응답값에서 planId 확인하실 수 있습니다!

2023-08-28 17:35 UTC, rovemin commented
> .girignore에 .idea/ 추가해야 할 것 같아요. 그리고 빌드 파일 clean하시고 커밋해주시는 게 좋을 것 같습니다.

.gitignore에 .idea/가 추가되어 있는데 반영되지 않은 것 같습니다. 이 부분은 다시 확인해보겠습니다.

2023-08-29 06:48 UTC, rovemin commented
코드 리뷰 반영 후 포스트맨 테스트 결과 이미지 업데이트 하였습니다.

2023-08-29 07:26 UTC, sunnyineverywhere requested changes
위에 두 가지만 한번 더 확인해주세요~ 고생하셨습니다.

2023-08-29 07:26 UTC, sunnyineverywhere commented on snapspot-api/src/main/java/snap/api/photographer/service/PhotographerService.java
> +
이 부분은 PhotographerService가 아닌 PhotographerDomainService에 있어야 할 메서드 같습니다

2023-08-29 07:26 UTC, sunnyineverywhere commented on snapspot-api/src/main/java/snap/api/plan/service/PlanService.java
> +        Photographer photographer = photographerService.findPhotographerEntity(photographerId);
여기

```java
...
photographerService.findPhotographerEntity(planRequestDto.getPhotographerId()
```
로 줄이면 어떨까요?

2023-08-29 07:26 UTC, sunnyineverywhere commented on snapspot-domain/src/main/java/snap/domains/plan/service/PlanDomainService.java
굿굿

2023-08-29 07:46 UTC, merged